### ISSUE TITLE
Als gebruiker wil ik goed op de hoogte worden gesteld van een specifieke 500 error pagina.

### ISSUE THREAD

**Issue by ItsDimitrie** [positive-healt-UVC/frontend#12]
Happy path : De gebruiker krijgt een gedetailleerde pagina te zien met een 500 error en word uitgelegd wat de vervolgstappen zijn.

Unhappy path : De gebruiker word niet duidelijk gemaakt welke error het is en wat de gebruiker verder moet doen.

Accepten criteria : Dit wordt behaald als de gebruiker goed geïnformeerd word over de error en weet wat de vervolgstappen zijn.

**Comment by djairo27** [comment]
Is goed
