### ISSUE TITLE
Als gebruiker wil ik dat ik goed op de hoogte word gesteld van een specifieke 404 error pagina.

### ISSUE THREAD

**Issue by ItsDimitrie** [positive-healt-UVC/frontend#13]
Happy path : De gebruiker krijgt een gedetailleerde pagina te zien met een 404 error en word uitgelegd wat de vervolgstappen zijn.

Unhappy path : De gebruiker word niet duidelijk gemaakt welke error het is en wat de gebruiker verder moet doen.

Accepten criteria : Dit wordt behaald als de gebruiker goed geïnformeerd word over de error en weet wat de vervolgstappen zijn.

**Comment by djairo27** [comment]
Is goed
