### ISSUE TITLE
Als gebruiker wil ik een knop waarmee ik naar de vorige pagina wordt geleid zodat ik snel en gemakkelijk door de applicatie heen kan navigeren

### ISSUE THREAD

**Issue by ItsDimitrie** [positive-healt-UVC/frontend#25]
Happy: wanneer ik als gebruiker op de verkeerde pagina druk, kan ik met een terug knop naar de vorige pagina  

Unhappy: wanneer ik als gebruiker op de verkeerde pagina druk, kan ik niet meer terug naar de vorige pagina met een terug knop 

Acceptance criteria: klaar als de gebruiker een knop heeft waarmee hij naar de vorige pagina kan gaan

**Comment by Willem-Arie** [comment]
Op dit moment is de route van de vorige pagina gehardcode. Maak dit dynamisch.

**Comment by ItsDimitrie** [comment]
Gefixt
