### ISSUE TITLE
Component Diagram deliverable voor woensdag.

### ISSUE THREAD

**Issue by ItsDimitrie** [positive-healt-UVC/frontend#7]

**Comment by Ali-A-Hamdan** [comment]
https://myhz.sharepoint.com/teams/PositiveHealth/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120001A972528EAF5CF43AA5762D8941459F7&id=%2Fteams%2FPositiveHealth%2FShared%20Documents%2FGeneral%2FSprint%201%2FPortfolio%2FComponentDiagram%2Fcomponentdiagram%5FV1%2Epng&parent=%2Fteams%2FPositiveHealth%2FShared%20Documents%2FGeneral%2FSprint%201%2FPortfolio%2FComponentDiagram (link naar v1)

**Comment by ItsDimitrie** [comment]
Het is een goed begin maar mis de volgende microservices in de backend:

Locaties
Activiteiten
Handicaps

Daarnaast zal ik deelnemers en Organisators samenvoegen tot "Users".

**Comment by Ali-A-Hamdan** [comment]
Link naar aangepaste diagram: https://myhz.sharepoint.com/teams/PositiveHealth/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120001A972528EAF5CF43AA5762D8941459F7&id=%2Fteams%2FPositiveHealth%2FShared%20Documents%2FGeneral%2FSprint%201%2FPortfolio%2FComponentDiagram%2Fcomponentdiagram%5FV2%2Epng&parent=%2Fteams%2FPositiveHealth%2FShared%20Documents%2FGeneral%2FSprint%201%2FPortfolio%2FComponentDiagram
