### ISSUE TITLE
USE-Case Diagram deliverable voor woensdag.

### ISSUE THREAD

**Issue by ItsDimitrie** [positive-healt-UVC/frontend#8]

**Comment by ItsDimitrie** [comment]
https://myhz.sharepoint.com/:f:/r/teams/PositiveHealth/Shared%20Documents/General/Sprint%201/Portfolio/Use-case%20diagram?csf=1&web=1&e=YrQtNT

**Comment by Willem-Arie** [comment]
https://myhz.sharepoint.com/:i:/r/teams/PositiveHealth/Shared%20Documents/General/Sprint%201/Portfolio/Use-case%20diagram/Use%20case-diagram%20V4.png?csf=1&web=1&e=gTz15T
